name: janus_client
description: A feature rich Janus Webrtc package
version: 2.4.2+mt.2
homepage: https://github.com/shivanshtalwar0/flutter_janus_client

environment:
  sdk: ^3.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

dependencies:
  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter
  flutter_webrtc: any
  path_provider: any
  http: any
  web_socket_channel: any
  uuid: any
  logging: any
